import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Navbar, { NavbarProvider } from "@/components/Navbar";
import HeaderLayout from "@/components/client/HeaderLayout";
import { QueryProvider } from "@/components/context/QueryContext";
import { RoleProvider } from "@/components/context/RoleContext";
// import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Restaurant Management System",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <QueryProvider>
            <RoleProvider>
              <NavbarProvider>
                <div className="w-full flex">
                  <Navbar />
                  <main className="flex-1 p-5">
                    <HeaderLayout />
                    {children}
                  </main>
                </div>
              </NavbarProvider>
            </RoleProvider>
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
