import { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link'
import React from 'react'

export const metadata: Metadata = {
  title: "Restaurant Management System - Home",
  description: "Generated by create next app",
};

export default async function Default() {
  return (
    <div className="w-full h-screen flex flex-col">
      <header className='w-full h-[50px] bg-white flex justify-end'>
        <div className="w-fit flex gap-x-5 px-10 text-black h-full items-center">
          <Link href={'/signup'}>SignUp</Link>
          <Link href={'/signin'}>SignIn</Link>
        </div>
      </header>
      <main className='flex-1 flex justify-center items-center flex-col relative'>
        <div className="w-full h-full absolute top-0 -z-[99] backdrop-blur-md bg-black/30">
          <Image src={'/img/texture-bg-1.jpg'} layout='fill' alt='bg' className='backdrop-blur-3xl'/>
        </div>
        <h1 className='font-bold text-5xl tracking-widest'>Restaurant Web</h1>
        <p className='mt-2'>Website for managing your restaurant order.</p>
      </main>
    </div>
  )
}
